# Generated by Django 5.1.2 on 2024-10-14 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Groom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Universal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GroomAttire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('groom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attire', to='you_and_me.groom')),
            ],
        ),
        migrations.CreateModel(
            name='GroomEssentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('groom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essentials', to='you_and_me.groom')),
            ],
        ),
        migrations.CreateModel(
            name='GroomStylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('groom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylist', to='you_and_me.groom')),
            ],
        ),
        migrations.CreateModel(
            name='Sarpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('bride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sarpo', to='you_and_me.bride')),
            ],
        ),
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('bride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylist', to='you_and_me.bride')),
            ],
        ),
        migrations.CreateModel(
            name='WeddingDress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('bride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_dress', to='you_and_me.bride')),
            ],
        ),
    ]
