# Generated by Django 5.1.2 on 2024-10-14 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('you_and_me', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Universal',
            new_name='UniversalCategory',
        ),
        migrations.CreateModel(
            name='UniversalSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='you_and_me.universalcategory')),
            ],
        ),
        migrations.CreateModel(
            name='UniversalSubSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_subcategories', to='you_and_me.universalsubcategory')),
            ],
        ),
    ]
