# Generated by Django 5.1.2 on 2024-10-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('you_and_me', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
