# Generated by Django 5.1.2 on 2024-10-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('you_and_me', '0005_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='additional_services/'),
        ),
        migrations.AddField(
            model_name='additionalservicesubcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='additional_service_subcategories/'),
        ),
        migrations.AddField(
            model_name='bride',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brides/'),
        ),
        migrations.AddField(
            model_name='groom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='grooms/'),
        ),
        migrations.AddField(
            model_name='groomattire',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groom_attire/'),
        ),
        migrations.AddField(
            model_name='groomessentials',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groom_essentials/'),
        ),
        migrations.AddField(
            model_name='groomstylist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groom_stylists/'),
        ),
        migrations.AddField(
            model_name='sarpo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sarpo/'),
        ),
        migrations.AddField(
            model_name='stylist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stylists/'),
        ),
        migrations.AddField(
            model_name='universalcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='universalsubcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategories/'),
        ),
        migrations.AddField(
            model_name='universalsubsubcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sub_subcategories/'),
        ),
        migrations.AddField(
            model_name='weddingdress',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wedding_dresses/'),
        ),
    ]
